FROM public.ecr.aws/lambda/python:3.12

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}

# Install the specified packages
RUN pip install -r requirements.txt

# Copy function code and dependencies
COPY binance_coint_analyzer.py ${LAMBDA_TASK_ROOT}
COPY db_helper_functions.py ${LAMBDA_TASK_ROOT}
COPY config.py ${LAMBDA_TASK_ROOT}

# Set the CMD to your handler 
CMD [ "binance_coint_analyzer.lambda_handler" ]